# Generated by Django 4.2.11 on 2024-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idhalaya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_meta',
            name='course_time_seconds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_meta',
            name='course_trainer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assesment',
            name='assesment_answer',
            field=models.CharField(choices=[(1, 'Answer 1 '), (2, 'Answer 2 '), (3, 'Answer 3 '), (4, 'Answer 4 ')], max_length=200),
        ),
        migrations.AlterField(
            model_name='assesment',
            name='assesment_question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assesment_feedback',
            name='feedback_text',
            field=models.TextField(),
        ),
    ]
