# Generated by Django 4.2.11 on 2024-05-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idhalaya', '0003_course_meta_course_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_meta',
            name='course_meta',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assesment',
            name='assesment_group',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('parents', 'Parents'), ('student', 'Students')], max_length=8),
        ),
        migrations.AlterField(
            model_name='assesment_feedback',
            name='feedback_group',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('parents', 'Parents'), ('student', 'Students')], max_length=8),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_group',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('parents', 'Parents'), ('student', 'Students')], max_length=8),
        ),
    ]
