# Generated by Django 4.2.11 on 2024-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idhalaya', '0004_course_meta_course_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='assesment_group',
            field=models.CharField(choices=[('parents', 'Parents'), ('teacher', 'Teacher'), ('student', 'Students')], max_length=8),
        ),
        migrations.AlterField(
            model_name='assesment_feedback',
            name='feedback_group',
            field=models.CharField(choices=[('parents', 'Parents'), ('teacher', 'Teacher'), ('student', 'Students')], max_length=8),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_group',
            field=models.CharField(choices=[('parents', 'Parents'), ('teacher', 'Teacher'), ('student', 'Students')], max_length=8),
        ),
    ]
